// =====================================================================
//  tb_mnist.sv  -  self-checking MNIST testbench for neural_net_top
//
//  Required stimulus files (generated by gen_weights.py):
//     mnist_images.mem  : NUM_IMAGES x 784 pixel bytes, hex
//     mnist_labels.mem  : NUM_IMAGES ground-truth labels, hex
//     ROM.txt           : 16 x 9-bit conv filters, binary
//     fc_weights.mem    : 10 x 169-bit FC weights, binary
//
//  Run:  iverilog -g2012 -o sim tb_mnist.sv <rtl files> && ./sim
//        +NIMG=200        limit the run to 200 images
//        +SHOW=5          ASCII-render the first 5 images
//        +VERBOSE         print a line for every image
// =====================================================================
`timescale 1ns/1ps

module tb_mnist();

    localparam int MAX_IMAGES = 1000;
    localparam int PIXELS     = 784;

    logic [7:0] input_stream;
    logic       clk, rst, start;
    logic [3:0] predicted_digit;
    logic       prediction_ready;

    neural_net_top #(
        .DATA_WIDTH(8),
        .IMAGE_SIZE(28)
    ) uut (
        .input_stream(input_stream),
        .clk(clk),
        .rst(rst),
        .start(start),
        .predicted_digit(predicted_digit),
        .prediction_ready(prediction_ready)
    );

    always #5 clk = ~clk;

    // ---------------- stimulus storage ----------------
    logic [7:0] images [0:MAX_IMAGES*PIXELS-1];
    logic [3:0] labels [0:MAX_IMAGES-1];

    int n_images = MAX_IMAGES;
    int show_n   = 3;
    bit verbose  = 0;

    // ---------------- scoreboard ----------------
    int correct      = 0;
    int total        = 0;
    int confusion [0:9][0:9];
    int per_digit_n  [0:9];
    int per_digit_ok [0:9];
    int timeouts     = 0;

    logic [3:0] captured;
    bit         got_result;

    // ---------------- helpers ----------------
    task automatic render(input int idx, input int lbl, input int pred);
        string line;
        begin
            $display("");
            $display("  image %0d   label = %0d   predicted = %0d   %s",
                     idx, lbl, pred, (lbl == pred) ? "OK" : "<-- MISS");
            for (int r = 0; r < 28; r++) begin
                line = "  ";
                for (int c = 0; c < 28; c++)
                    line = {line, (images[idx*PIXELS + r*28 + c] >= 8'd128) ? "##" : ". "};
                $display("%s", line);
            end
        end
    endtask

    task automatic run_image(input int idx);
        int guard;
        begin
            got_result = 1'b0;

            @(posedge clk); #1 start = 1'b1;
            @(posedge clk); #1 start = 1'b0;

            for (int p = 0; p < PIXELS; p++) begin
                @(posedge clk);
                #1 input_stream = images[idx*PIXELS + p];
            end

            // prediction lands a few cycles after the last pixel
            // Poll 1ns after each edge, once all non-blocking updates have
            // settled. Sampling AT the edge is a race whose outcome differs
            // between simulators, so this stays portable.
            guard = 0;
            while (!got_result && guard < 200) begin
                @(posedge clk);
                #1;
                if (prediction_ready) begin
                    captured   = predicted_digit;
                    got_result = 1'b1;
                end
                guard++;
            end
            if (!got_result) begin
                timeouts++;
                $display("  ** TIMEOUT on image %0d - no prediction_ready", idx);
            end

            @(posedge clk); #1 input_stream = 8'd0;
            repeat (4) @(posedge clk);
        end
    endtask

    // ---------------- main ----------------
    int lbl, pred;
    real acc;
    string bar;

    initial begin
        $readmemh("mnist_images.mem", images);
        $readmemh("mnist_labels.mem", labels);

        if (!$value$plusargs("NIMG=%d", n_images)) n_images = MAX_IMAGES;
        if (!$value$plusargs("SHOW=%d", show_n))   show_n   = 3;
        verbose = $test$plusargs("VERBOSE");
        if (n_images > MAX_IMAGES) n_images = MAX_IMAGES;

        for (int a = 0; a < 10; a++) begin
            per_digit_n[a]  = 0;
            per_digit_ok[a] = 0;
            for (int b = 0; b < 10; b++) confusion[a][b] = 0;
        end

        clk = 0; rst = 1; start = 0; input_stream = 0; got_result = 0;
        repeat (4) @(posedge clk);
        #1 rst = 0;
        repeat (2) @(posedge clk);

        $display("");
        $display("=======================================================");
        $display("  MNIST inference on neural_net_top  -  %0d images", n_images);
        $display("=======================================================");

        for (int idx = 0; idx < n_images; idx++) begin
            run_image(idx);

            lbl  = labels[idx];
            pred = captured;
            total++;
            per_digit_n[lbl]++;
            confusion[lbl][(pred > 9) ? 9 : pred]++;
            if (pred == lbl) begin
                correct++;
                per_digit_ok[lbl]++;
            end

            if (idx < show_n)
                render(idx, lbl, pred);
            else if (verbose)
                $display("  [%4d] label=%0d  pred=%0d  %s  running acc = %0.2f%%",
                         idx, lbl, pred, (pred == lbl) ? "OK  " : "MISS",
                         100.0 * correct / total);
            else if ((idx + 1) % 100 == 0)
                $display("  ... %0d images, running accuracy = %0.2f%%",
                         idx + 1, 100.0 * correct / total);
        end

        // ---------------- report ----------------
        $display("");
        $display("=======================================================");
        $display("  CONFUSION MATRIX   (rows = true label, cols = predicted)");
        $display("=======================================================");
        $display("        0    1    2    3    4    5    6    7    8    9");
        for (int a = 0; a < 10; a++) begin
            $write("   %0d |", a);
            for (int b = 0; b < 10; b++) $write("%5d", confusion[a][b]);
            $write("\n");
        end

        $display("");
        $display("=======================================================");
        $display("  PER-DIGIT ACCURACY");
        $display("=======================================================");
        for (int a = 0; a < 10; a++) begin
            acc = (per_digit_n[a] == 0) ? 0.0 :
                  100.0 * per_digit_ok[a] / per_digit_n[a];
            bar = "";
            for (int t = 0; t < acc / 2.5; t++) bar = {bar, "#"};
            $display("   digit %0d : %3d/%3d  %6.2f%%  %s",
                     a, per_digit_ok[a], per_digit_n[a], acc, bar);
        end

        $display("");
        $display("=======================================================");
        $display("  OVERALL : %0d / %0d correct  =  %0.2f%%",
                 correct, total, 100.0 * correct / total);
        if (timeouts > 0)
            $display("  WARNING : %0d images produced no prediction", timeouts);
        $display("=======================================================");
        $display("");

        $finish;
    end

endmodule
